### ISSUE TITLE
Required pytorch version is wrong

### ISSUE THREAD

**Issue by Yikai-Wang** [tankche1/Image-Deformation-Meta-Networks-for-One-Shot-Learning#2]
When I use pytorch=0.4.0, the code will report an error:
```
Traceback (most recent call last):
  File "onlyBasetwoLoss.py", line 621, in <module>
    GNet = train_model(GNet, num_epochs=120)
  File "onlyBasetwoLoss.py", line 485, in train_model
    AInputs, BInputs, ABLabels, ABReals = iterateMix(supportInputs,supportFeatures,supportLabels,supportReals,ways=ways)
  File "onlyBasetwoLoss.py", line 394, in iterateMix
    AImages[i*args.shots*(1+args.augnum)+j*(args.augnum+1)+1+k] = torch.flip(supportImages[i*args.shots+j],[2])
AttributeError: 'module' object has no attribute 'flip'
```
After I update pytorch to 0.4.1, the code can run properly.

**Comment by ztf-ucas** [comment]
I have also noticed this problem and ran this code with Pytorch 1.1.0.
